name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Yarn install
        run: yarn install

      - name: ESLint
        run: yarn eslint --ignore-pattern=test .

      - name: Prettier
        if: ${{ !cancelled() }}
        run: yarn prettier --check . '!test'

      - name: Test
        if: ${{ !cancelled() }}
        working-directory: ./test
        run: node compare-test.js

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
