name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Pnpm install
        run: pnpm install

      - name: ESLint
        run: |
          cd lint && pnpm eslint .
          cd test && pnpm eslint test.js

      - name: Prettier
        if: ${{ !cancelled() }}
        run: |
          cd lint && pnpm prettier --check .
          cd test && pnpm prettier --check test.js

      - name: Test
        if: ${{ !cancelled() }}
        working-directory: ./lint
        run: pnpm test

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make cjs version
        working-directory: ./lint
        run: pnpm build

      - name: Publish package
        uses: JS-DevTools/npm-publish@v2
        with:
          package: ./lint
          token: ${{ secrets.NPM_TOKEN }}
