name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Pnpm install
        run: pnpm install

      - name: ESLint
        working-directory: ./lint
        run: pnpm eslint .

      - name: Prettier
        working-directory: ./lint
        if: ${{ !cancelled() }}
        run: pnpm prettier --check .

      - name: Test
        if: ${{ !cancelled() }}
        working-directory: ./test
        run: node compare-test.js

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make cjs version
        working-directory: ./lint
        run: pnpm rollup index.js --file index.cjs --format cjs

      - name: Publish package
        uses: JS-DevTools/npm-publish@v2
        with:
          package: ./lint
          token: ${{ secrets.NPM_TOKEN }}
